# .github/FUNDING.yml
# Enable GitHub Sponsors for this repo
# To activate: visit https://github.com/sponsors/Agnuxo1

github: [Agnuxo1]
# patreon: # if activated later
# open_collective: # if activated later
custom: ["https://www.p2pclaw.com/donate", "https://github.com/sponsors/Agnuxo1"]
